"""create sources, import_jobs, catalog_items

Revision ID: 0d784ce0fa89
Revises: 
Create Date: 2026-09-14 01:41:36.497506

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d784ce0fa89'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('M3U_URL', 'PROVIDER_CREDENTIALS', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('m3u_url', sa.String(), nullable=True),
    sa.Column('provider_dns', sa.String(), nullable=True),
    sa.Column('provider_username', sa.String(), nullable=True),
    sa.Column('provider_password', sa.String(), nullable=True),
    sa.Column('connection_state', sa.Enum('NEVER_SYNCED', 'SYNCED', 'ERROR', name='connectionstate', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELLED', name='importjobstatus', native_enum=False), nullable=False),
    sa.Column('current_step', sa.Enum('ACQUIRING', 'PARSING', 'CLASSIFYING', 'PUBLISHING', 'DONE', name='importstep', native_enum=False), nullable=False),
    sa.Column('entries_read', sa.Integer(), nullable=False),
    sa.Column('channels_count', sa.Integer(), nullable=False),
    sa.Column('movies_count', sa.Integer(), nullable=False),
    sa.Column('series_count', sa.Integer(), nullable=False),
    sa.Column('episodes_count', sa.Integer(), nullable=False),
    sa.Column('unclassified_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('request_key', sa.String(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('CHANNEL', 'MOVIE', 'SERIES', 'EPISODE', 'UNCLASSIFIED', name='catalogitemkind', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('original_group', sa.String(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('playback_url', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_items')
    op.drop_table('import_jobs')
    op.drop_table('sources')
    # ### end Alembic commands ###
