"""add provider fields to sources and catalog_items

Revision ID: 307ba52e3904
Revises: 0d784ce0fa89
Create Date: 2026-09-18 07:45:16.101736

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '307ba52e3904'
down_revision: str | Sequence[str] | None = '0d784ce0fa89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('provider_stream_id', sa.String(), nullable=True))
    op.add_column('catalog_items', sa.Column('provider_category_id', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('provider_import_mode', sa.Enum('XTREAM_API', 'LEGACY_M3U', name='providerimportmode', native_enum=False), nullable=True))
    op.add_column('sources', sa.Column('provider_allowed_formats', sa.JSON(), nullable=True))
    op.add_column('sources', sa.Column('provider_migrated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'provider_migrated_at')
    op.drop_column('sources', 'provider_allowed_formats')
    op.drop_column('sources', 'provider_import_mode')
    op.drop_column('catalog_items', 'provider_category_id')
    op.drop_column('catalog_items', 'provider_stream_id')
    # ### end Alembic commands ###
